// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_agTrendTMB_TMBExports
#include <TMB.hpp>
#include "disc_norm_gp.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "disc_norm_gp") {
    return disc_norm_gp(this);
  } else {
    error("Unknown model.");
  }
  return 0;
}
